# Generated by Django 3.2.3 on 2021-05-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('min_age', models.IntegerField(verbose_name='Idade mínima')),
            ],
            options={
                'verbose_name': 'Grupo de Atendimento',
                'verbose_name_plural': 'Grupos de Atendimento',
                'ordering': ['-min_age'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('address', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('neighborhood', models.CharField(max_length=200, verbose_name='Bairro')),
                ('city', models.CharField(max_length=200, verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Ponto de Vacinação',
                'verbose_name_plural': 'Pontos de Vacinação',
                'ordering': ['name', 'city'],
            },
        ),
    ]
