# Generated by Django 3.2.3 on 2021-06-01 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Sala')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.vaccinationcenter', verbose_name='Local')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('slot', models.TimeField(verbose_name='Horário')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('manufacturer', models.CharField(max_length=200, verbose_name='Fabricante')),
            ],
            options={
                'verbose_name': 'Vacina',
                'verbose_name_plural': 'Vacinas',
            },
        ),
        migrations.CreateModel(
            name='SchedulingCitizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('a', 'Agendado'), ('v', 'Vacinado'), ('c', 'Cancelado')], max_length=200)),
                ('citizen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vaccination.citizen', verbose_name='Cidadão')),
                ('scheduling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.scheduling', verbose_name='Agendamento')),
            ],
            options={
                'verbose_name': 'AgendamentoCidadão',
                'verbose_name_plural': 'AgendamentosCidadãos',
            },
        ),
        migrations.AddField(
            model_name='scheduling',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.vaccine'),
        ),
        migrations.CreateModel(
            name='RoomScheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_vacancies', models.IntegerField(verbose_name='Vagas')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.room')),
                ('scheduling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.scheduling')),
            ],
            options={
                'verbose_name': 'SalaAgendamento',
                'verbose_name_plural': 'SalaAgendamentos',
            },
        ),
    ]
