# Generated by Django 3.2.3 on 2021-05-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaccinationcenter',
            options={'ordering': ['name', 'city'], 'verbose_name': 'Local de Vacinação', 'verbose_name_plural': 'Locais de Vacinação'},
        ),
        migrations.RemoveField(
            model_name='vaccinationcenter',
            name='id',
        ),
        migrations.AddField(
            model_name='vaccinationcenter',
            name='cnes',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='CNES'),
            preserve_default=False,
        ),
    ]
