# Generated by Django 3.2.3 on 2021-06-01 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0002_auto_20210531_2244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name'], 'verbose_name': 'Sala', 'verbose_name_plural': 'Salas'},
        ),
        migrations.AlterModelOptions(
            name='roomscheduling',
            options={'verbose_name': 'Sala-Agendamento', 'verbose_name_plural': 'Sala-Agendamentos'},
        ),
        migrations.AlterModelOptions(
            name='scheduling',
            options={'ordering': ['-date'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterModelOptions(
            name='schedulingcitizen',
            options={'verbose_name': 'Agendamento-Cidadão', 'verbose_name_plural': 'Agendamentos-Cidadãos'},
        ),
        migrations.AlterModelOptions(
            name='vaccine',
            options={'ordering': ['name'], 'verbose_name': 'Vacina', 'verbose_name_plural': 'Vacinas'},
        ),
        migrations.AddField(
            model_name='roomscheduling',
            name='num_available_vacancies',
            field=models.IntegerField(default=45, verbose_name='Vagas disponíveis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduling',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vaccination.servicegroup', verbose_name='Grupo de Atendimento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.vaccine', verbose_name='Vacina'),
        ),
    ]
