# Generated by Django 3.2.3 on 2021-06-01 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0004_alter_citizen_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomscheduling',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roomscheduling',
            name='scheduling',
        ),
        migrations.AddField(
            model_name='scheduling',
            name='center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vaccination.vaccinationcenter', verbose_name='Local'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduling',
            name='num_available_vacancies',
            field=models.IntegerField(default=1, verbose_name='Vagas disponíveis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduling',
            name='num_vacancies',
            field=models.IntegerField(default=1, verbose_name='Vagas'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomScheduling',
        ),
    ]
