# Generated by Django 3.2.3 on 2021-06-02 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0005_auto_20210601_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaccinationcenter',
            options={'ordering': ['city', 'name'], 'verbose_name': 'Local de Vacinação', 'verbose_name_plural': 'Locais de Vacinação'},
        ),
        migrations.AddField(
            model_name='schedulingcitizen',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedulingcitizen',
            name='status',
            field=models.CharField(choices=[('a', 'Agendado'), ('v', 'Vacinado'), ('c', 'Cancelado')], default='a', max_length=200),
        ),
    ]
