version: "3.9"
services:
  db:
    image: library/postgres:13.3
    container_name: vaccination_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5436:5432'
